### ISSUE TITLE
First stable version

### ISSUE THREAD

**Issue by andrekop** [vginert/android-things-dht-driver#1]
Thank you for hopping on the train early and implementing what appears to be the very first third party Android Things user driver on GitHub.

Can the "develop" branch already be used for testing? I know it's very early, but I tried it and received the following error upon starting:
``` java
W/peripheralman: [1217/211233:WARNING:gpio_driver_sysfs.cc(107)] Failed to set the value of the GPIO. Is it configured as output?
```
``` java
Error configuring sensor
com.google.android.things.pio.PioException: android.os.ServiceSpecificException: BCM19 is already in use
at com.google.android.things.pio.GpioImpl.<init>(GpioImpl.java:53)
at com.google.android.things.pio.PeripheralManagerService.openGpio(PeripheralManagerService.java:169)
at com.vginert.android.things.dhtdriver.Dhtxx.<init>(Dhtxx.java:42)
at com.vginert.android.things.dhtdriver.DhtxxHumidityAndTemperatureDriver.<init>(DhtxxHumidityAndTemperatureDriver.java:41)
```

**Comment by pflammertsma** [comment]
I've done some testing as well, and made some headway, but I believe the DHT is simply incompatible with Android Things as the transmission data rate is too fast for Android Things to read from the BCM input pin.

[The documentation](https://cdn-learn.adafruit.com/downloads/pdf/dht.pdf) says it works for any board with "microsecond processing", but the RPI3 running Android Things 0.2 preview only has millisecond timing on GPIO.

**Comment by andrekop** [comment]
I also tried to write a RF 433MHz driver for AT in Java but ultimately gave up as the IO timings were very inconsistent. Hopefully, that's not a general limitation of Android Things and will be improved later on.

I haven't tested it but the native PIO API (C/C++) could be faster and work better for these cases ([https://developer.android.com/things/sdk/pio/native.html](https://developer.android.com/things/sdk/pio/native.html)).

**Comment by pflammertsma** [comment]
I was actually in the process of testing the NDK, but read somewhere else
that the performance isn't much better. There was somebody that had an
implementation using fprint() to write directly on to the device, and it
seemed to have better performance in native code. I'm not extremely
familiar with that sort of thing, though.

In any case, I sincerely believe that these sorts of asynchronous clock
issues are really dumb and antiquated approaches, and much rather prefer
I2C. The hardware is a bit more expensive, but it sure gives less headache!
